language: python
python:
  - "3.6"

branches:
  only:
    - master
    - starter
    - issue-9-travis-pytest
    - issue-11-add-Black-formatter

install:
  - "pip install -r requirements.txt"

script:
  - "python perftestnotebook.py --config=testing/configs/config_single_json_test.yaml -ni"
  - "python -m black -l 100 ."
  - "python -m pytest -v testing/tests/"
