language: python
python:
  - "3.6"

branches:
  only:
    - master
    - starter
    - issue-17-unit-tests

install:
  - "pip install -r requirements.txt"

script:
  - "python -m black -l 100 ."
  - "python perftestnotebook.py --config=testing/configs/config_single_json_test.yaml"
  - "python -m pytest -v testing/tests/"
