language: python
python:
  - "3.6"

branches:
  only:
  - master
  - dev
  - issue-9

install:
  - "pip install -r requirements.txt"

script:
- "python -m pytest -m first_run --capture=no tests"
- "python -m pytest -m 'not first_run' --capture=no tests"