language: python
python:
  - "3.6"

branches:
  only:
  - master
  - dev
  - issue-9

install:
  - "wget ${ES_DOWNLOAD_URL}"
  - "tar -xzf elasticsearch-${ES_VERSION}.tar.gz"
  - "sudo cp -f tests/travis/elasticsearch-${ES_VERSION}.yml ./elasticsearch-${ES_VERSION}/config/elasticsearch.yml"
  - "./elasticsearch-${ES_VERSION}/bin/elasticsearch &"
  - "pip install -r tests/requirements.txt"
  - "pip install -r requirements.txt"
  - "wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200"

script:
- "python -m pytest -m first_run --capture=no tests"
- "python -m pytest -m 'not first_run' --capture=no tests"